### create player
POST http://localhost:9000/User/create
Content-Type: application/json

{
  "username": "TestAdmin",
  "email": "test@admin.dk",
  "passwordhash": "Password2!",
  "roleName": "Admin"
}

###

PATCH http://localhost:9000/User/1
Content-Type: application/json

{
  "username": "newUsername",
  "email": "test2@user.dk",
  "newPassword": "NewSecurePassword123!"
}

###

GET http://localhost:9000/User/getAll
Content-Type: application/json

###

GET http://localhost:9000/User/getById/1
Content-Type: application/json

###

DELETE http://localhost:9000/User/2
Content-Type: application/json