### create user
POST http://localhost:9000/User/create
Content-Type: application/json

{
  "username": "TestUser",
  "email": "test2@user.dk",
  "passwordhash": "Password1!",
  "roleName": "Player"
}

###

PATCH http://localhost:9000/User/1
Content-Type: application/json

{
  "username": "newUsername",
  "email": "test2@user.dk",
  "newPassword": "NewSecurePassword123!"
}

###

GET http://localhost:9000/User/getAll
Content-Type: application/json

###

GET http://localhost:9000/User/1
Content-Type: application/json

###